# Generated by Django 4.2.7 on 2023-11-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='rental_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='realestate.rentalasset'),
        ),
    ]
