# Generated by Django 4.2.7 on 2023-11-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_alter_price_rental_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='tenant',
        ),
        migrations.AddField(
            model_name='contract',
            name='tenants',
            field=models.ManyToManyField(to='realestate.tenant'),
        ),
    ]
