services:
  # Redis service for celery stuff
  redis:
    restart: unless-stopped
    image: redis:7.2.0-alpine
    expose:
      - 6379
      
  rentake-backend:
    # Build with the local Dockerfile in .devcontainer
    build:
      context: ../  # Path to the project's root folder so that the Dockerfile commands can access the project
      dockerfile: ./.devcontainer/Dockerfile  # Path to the Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      # The root in this case is the parent directory of the parent directory of this docker compose
      - ../../:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
 
